### ISSUE TITLE
Is it tested?

### ISSUE THREAD

**Issue by joaoantoniocardoso** [jackw01/arduino-pid-autotuner#5]
Hi! I was looking for some simple PID auto-tune implementation example and here I am.

I would be implementing something like this by myself, but after reading it I am thinking that possibly I could collaborate and use it.

So I want to know if this is already tested and if you are accepting small contributions to your code.

Cheers!

**Comment by jackw01** [comment]
I have personally used this code for tuning PID loops for motor speed control with rotary encoders so far. I'm not sure about anyone else using this specific library, but I know that some 3D printer firmwares use the same algorithm for temperature control PID tuning. 

I am accepting contributions.
