### ISSUE TITLE
question about loopinterval

### ISSUE THREAD

**Issue by Thulfiqar92** [jackw01/arduino-pid-autotuner#6]
Dear Jack, Thank you for posting this library, I have a question about the "loopinterval" and the "while (micros() - microseconds < 500) delayMicroseconds(1)"
my thermocouple module requires a delay of at least 500ms to get a new reading from the thermocouple,
**What should type in the loopinterval and the delayMicroseconds()?**
would you please check the code to see if what I did right or wrong? Thank you

`#include <pidautotuner.h>
#include <MAX6675_Thermocouple.h>
#include <dimmable_light.h>
#define PWM1  11
#define zerocross  2 
DimmableLight light(PWM1);

int DO = 5;
int CS = 7;
int CLK = 6;
MAX6675_Thermocouple thermocouple(CLK, CS, DO);
double input, output,kp,ki,kd;

void setup() {
   delay(3000);
    PIDAutotuner tuner = PIDAutotuner();
  Serial.begin(9600);
  DimmableLight::setSyncPin(zerocross);
  DimmableLight::begin();
    // Set the target value to tune to
    // This will depend on what you are tuning. This should be set to a value within
    // the usual range of the setpoint. For low-inertia systems, values at the lower
    // end of this range usually give better results. For anything else, start with a
    // value at the middle of the range.
    tuner.setTargetInputValue(150);

    // Set the loop interval in microseconds
    // This must be the same as the interval the PID control loop will run at
    tuner.setLoopInterval(500);

    // Set the output range
    // These are the minimum and maximum possible output values of whatever you are
    // using to control the system (Arduino analogWrite, for example, is 0-255)
    tuner.setOutputRange(0, 255);

    // Set the Ziegler-Nichols tuning mode
    // Set it to either PIDAutotuner::ZNModeBasicPID, PIDAutotuner::ZNModeLessOvershoot,
    // or PIDAutotuner::ZNModeNoOvershoot. Defaults to ZNModeNoOvershoot as it is the
    // safest option.
    tuner.setZNMode(PIDAutotuner::ZNModeNoOvershoot);

    // This must be called immediately before the tuning loop
    // Must be called with the current time in microseconds
    tuner.startTuningLoop(micros());

    // Run a loop until tuner.isFinished() returns true
    long microseconds;
    while (!tuner.isFinished()) {

        // This loop must run at the same speed as the PID control loop being tuned
        long prevMicroseconds = microseconds;
        microseconds = micros();

        // Get input value here (temperature, encoder position, velocity, etc)
        double input = thermocouple.readCelsius();

        // Call tunePID() with the input value and current time in microseconds
        double output = tuner.tunePID(input, microseconds);

        // Set the output - tunePid() will return values within the range configured
        // by setOutputRange(). Don't change the value or the tuning results will be
        // incorrect.
        light.setBrightness(output);

        // This loop must run at the same speed as the PID control loop being tuned
        while (micros() - microseconds < 500) delayMicroseconds(1);
       
      Serial.print("output= ");
  Serial.println(output);
  Serial.print("Temp= ");
  Serial.println(input);

  Serial.print("kp= ");
  Serial.println(kp);
    Serial.print("ki= ");
  Serial.println(ki);
      Serial.print("kd= ");
  Serial.println(kd);
      delay(500);
    }

    // Turn the output off here.
    light.setBrightness(0);

    // Get PID gains - set your PID controller's gains to these
     kp = tuner.getKp();
     ki = tuner.getKi();
     kd = tuner.getKd();
}

void loop() {

      Serial.print("output= ");
  Serial.println(output);
  Serial.print("Temp= ");
  Serial.println(input);

  Serial.print("kp= ");
  Serial.println(kp);
    Serial.print("ki= ");
  Serial.println(ki);
      Serial.print("kd= ");
  Serial.println(kd);
  

  delay(500);
}`

**Comment by jackw01** [comment]
The loop interval should be 500000 microseconds, which is equal to 500 milliseconds. Remove the serial print and 500ms delay code from the while loop since the loop already has a delay in the line `while (micros() - microseconds < loopInterval) delayMicroseconds(1);`. 

```
...
    long loopInterval = 500000;

    PIDAutotuner tuner = PIDAutotuner();

    // Set the target value to tune to
    // This will depend on what you are tuning. This should be set to a value within
    // the usual range of the setpoint. For low-inertia systems, values at the lower
    // end of this range usually give better results. For anything else, start with a
    // value at the middle of the range.
    tuner.setTargetInputValue(150);

    // Set the loop interval in microseconds
    // This must be the same as the interval the PID control loop will run at
    tuner.setLoopInterval(loopInterval);

    // Set the output range
    // These are the minimum and maximum possible output values of whatever you are
    // using to control the system (Arduino analogWrite, for example, is 0-255)
    tuner.setOutputRange(0, 255);

    // Set the Ziegler-Nichols tuning mode
    // Set it to either PIDAutotuner::ZNModeBasicPID, PIDAutotuner::ZNModeLessOvershoot,
    // or PIDAutotuner::ZNModeNoOvershoot. Defaults to ZNModeNoOvershoot as it is the
    // safest option.
    tuner.setZNMode(PIDAutotuner::ZNModeNoOvershoot);

    // This must be called immediately before the tuning loop
    // Must be called with the current time in microseconds
    tuner.startTuningLoop(micros());

    // Run a loop until tuner.isFinished() returns true
    long microseconds;
    while (!tuner.isFinished()) {

        // This loop must run at the same speed as the PID control loop being tuned
        long prevMicroseconds = microseconds;
        microseconds = micros();

        // Get input value here (temperature, encoder position, velocity, etc)
        double input = thermocouple.readCelsius();

        // Call tunePID() with the input value and current time in microseconds
        double output = tuner.tunePID(input, microseconds);

        // Set the output - tunePid() will return values within the range configured
        // by setOutputRange(). Don't change the value or the tuning results will be
        // incorrect.
        light.setBrightness(output);

        // This loop must run at the same speed as the PID control loop being tuned
        while (micros() - microseconds < loopInterval) delayMicroseconds(1);
    }

    // Turn the output off here.
    light.setBrightness(0);

    // Get PID gains - set your PID controller's gains to these
    double kp = tuner.getKp();
    double ki = tuner.getKi();
    double kd = tuner.getKd();
}
```
